-- MySQL Script generated by MySQL Workbench
-- Sat May 21 20:33:19 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- DROP para apagar o Banco de Dados
-- -----------------------------------------------------

DROP SCHEMA IF EXISTS `SportFitness`;

-- -----------------------------------------------------
-- Schema SportFitness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SportFitness` DEFAULT CHARACTER SET utf8 ;
USE `SportFitness` ;

-- -----------------------------------------------------
-- Table `SportFitness`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`usuarios` (
  `id_login` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `isAdmin` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_login`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Usuario padrao do sistema
-- -----------------------------------------------------
INSERT INTO usuarios(nome, senha, isAdmin) VALUES
('master', 'eb0a191797624dd3a48fa681d3061212', 'Administrador');


-- -----------------------------------------------------
-- Table `SportFitness`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`estados` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`cidades` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `idEstado` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cidade`),
  INDEX `fk_cidades_estados1_idx` (`idEstado` ASC),
  CONSTRAINT `fk_cidades_estados1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `SportFitness`.`estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`alunos` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `telefoneRes` VARCHAR(15) NULL,
  `telefoneCel` VARCHAR(15) NULL,
  `dataNasc` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `idCidade` INT NOT NULL,
  `cep` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `observacao` VARCHAR(200) NULL,
  `senha` VARCHAR(32) NOT NULL,
  `idUsuario` INT,
  PRIMARY KEY (`id_aluno`),
  INDEX `fk_alunos_usuarios1_idx` (`idUsuario` ASC),
  INDEX `fk_alunos_cidades1_idx` (`idCidade` ASC),
  CONSTRAINT `fk_alunos_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `SportFitness`.`usuarios` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_cidades1`
    FOREIGN KEY (`idCidade`)
    REFERENCES `SportFitness`.`cidades` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`grupoMuscular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`grupoMuscular` (
  `id_grupoMuscular` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_grupoMuscular`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`exercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`exercicios` (
  `id_exercicio` INT NOT NULL AUTO_INCREMENT,
  `idGrupoMuscular` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_exercicio`),
  INDEX `fk_exercicios_grupoMuscular1_idx` (`idGrupoMuscular` ASC),
  CONSTRAINT `fk_exercicios_grupoMuscular1`
    FOREIGN KEY (`idGrupoMuscular`)
    REFERENCES `SportFitness`.`grupoMuscular` (`id_grupoMuscular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`objetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`objetivo` (
  `id_objetivo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_objetivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`treinadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`treinadores` (
  `id_treinador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `telefoneRes` VARCHAR(15) NULL,
  `telefoneCel` VARCHAR(15) NULL,
  `dataNasc` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `cep` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `salario` DOUBLE NOT NULL,
  `observacao` VARCHAR(200) NULL,
  PRIMARY KEY (`id_treinador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`planoTreino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`planoTreino` (
  `id_planoTreino` INT NOT NULL AUTO_INCREMENT,
  `idAluno` INT NOT NULL,
  `idTreinador` INT NOT NULL,
  `idObjetivo` INT NOT NULL,
  `dataInicio` VARCHAR(15) NOT NULL,
  `vezesSemana` INT NOT NULL,
  `situacao` TINYINT(1) NULL,
  PRIMARY KEY (`id_planoTreino`),
  INDEX `fk_PlanoTreino_Objetivo1_idx` (`idObjetivo` ASC),
  INDEX `fk_PlanoTreino_alunos1_idx` (`idAluno` ASC),
  INDEX `fk_PlanoTreino_treinadores1_idx` (`idTreinador` ASC),
  CONSTRAINT `fk_PlanoTreino_Objetivo1`
    FOREIGN KEY (`idObjetivo`)
    REFERENCES `SportFitness`.`objetivo` (`id_objetivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlanoTreino_alunos1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `SportFitness`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlanoTreino_treinadores1`
    FOREIGN KEY (`idTreinador`)
    REFERENCES `SportFitness`.`treinadores` (`id_treinador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`fichaTreino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`fichaTreino` (
  `id_fichaTreino` INT NOT NULL AUTO_INCREMENT,
  `idPlanoTreino` INT NOT NULL,
  `data` VARCHAR(15) NOT NULL,
  `nomeFicha` CHAR(1) NOT NULL,
  `numeroTreinos` INT NOT NULL,
  `numeroTreinosRealizados` INT NULL,
  `situacao` TINYINT(1) NULL,
  PRIMARY KEY (`id_fichaTreino`),
  INDEX `fk_FichaTreino_PlanoTreino1_idx` (`idPlanoTreino` ASC),
  CONSTRAINT `fk_FichaTreino_PlanoTreino1`
    FOREIGN KEY (`idPlanoTreino`)
    REFERENCES `SportFitness`.`planoTreino` (`id_planoTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`fichaDetalhe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`fichaDetalhe` (
  `id_fichaDetalhe` INT NOT NULL AUTO_INCREMENT,
  `idFichaTreino` INT NOT NULL,
  `idExercicio` INT NOT NULL,
  `series` INT NOT NULL,
  `repeticoes` INT NOT NULL,
  `carga` INT NOT NULL,
  `intervalo` INT NOT NULL,
  PRIMARY KEY (`id_fichaDetalhe`),
  INDEX `fk_treinos_exercicios1_idx` (`idExercicio` ASC),
  INDEX `fk_FichaDetalhe_FichaTreino1_idx` (`idFichaTreino` ASC),
  CONSTRAINT `fk_treinos_exercicios1`
    FOREIGN KEY (`idExercicio`)
    REFERENCES `SportFitness`.`exercicios` (`id_exercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FichaDetalhe_FichaTreino1`
    FOREIGN KEY (`idFichaTreino`)
    REFERENCES `SportFitness`.`fichaTreino` (`id_fichaTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`avaliacoes` (
  `id_avaliacao` INT NOT NULL AUTO_INCREMENT,
  `idAluno` INT NOT NULL,
  `data` VARCHAR(15) NOT NULL,
  `sexo` VARCHAR(12) NOT NULL,
  `peso` DOUBLE NOT NULL,
  `altura` DOUBLE NOT NULL,
  `percentualArterial` DOUBLE NOT NULL,
  `percentualGordura` DOUBLE NOT NULL,
  `torax` DOUBLE NOT NULL,
  `cintura` DOUBLE NOT NULL,
  `abdome` DOUBLE NOT NULL,
  `quadril` DOUBLE NOT NULL,
  `antebraco_direito` DOUBLE NOT NULL,
  `antebraco_esquerdo` DOUBLE NOT NULL,
  `braco_direito` DOUBLE NOT NULL,
  `braco_esquerdo` DOUBLE NOT NULL,
  `coxa_direita` DOUBLE NOT NULL,
  `coxa_esquerda` DOUBLE NOT NULL,
  `panturrilha_direita` DOUBLE NOT NULL,
  `panturrilha_esquerda` DOUBLE NOT NULL,
  `gorduraIdeal` DOUBLE NOT NULL,
  `pesoGordo` DOUBLE NOT NULL,
  `pesoDesejavel` DOUBLE NOT NULL,
  `gorduraAtual` DOUBLE NOT NULL,
  `pesoMagro` DOUBLE NOT NULL,
  `pesoResidual` DOUBLE NOT NULL,
  `situacao` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_avaliacao`),
  INDEX `fk_avaliacao_alunos1_idx` (`idAluno` ASC),
  CONSTRAINT `fk_avaliacao_alunos1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `SportFitness`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`noticias` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(15) NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `texto` VARCHAR(1000) NOT NULL,
  `idUsuario` INT,
  PRIMARY KEY (`id_noticia`),
  INDEX `fk_noticias_usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_noticias_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `SportFitness`.`usuarios` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportFitness`.`frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SportFitness`.`frequencia` (
  `id_Frequencia` INT NOT NULL AUTO_INCREMENT,
  `idAluno` INT NOT NULL,
  `idTreino` INT NOT NULL,
  `data` VARCHAR(15) NOT NULL,
  `horaEntrada` VARCHAR(15) NOT NULL,
  `horaSaida` VARCHAR(15) NOT NULL,
  `tempoPermanencia` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_Frequencia`),
  INDEX `fk_Frequencia_alunos1_idx` (`idAluno` ASC),
  INDEX `fk_frequencia_fichaTreino1_idx` (`idTreino` ASC),
  CONSTRAINT `fk_Frequencia_alunos1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `SportFitness`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frequencia_fichaTreino1`
    FOREIGN KEY (`idTreino`)
    REFERENCES `SportFitness`.`fichaTreino` (`id_fichaTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
